version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: ./.circleci/build.sh

workflows:
  version: 2

  build_on_push:
    jobs:
      - build:
          context: docker

  build_latest:
    triggers:
      - schedule:
          cron: "0 12 * * 1,3"
          filters:
            branches:
              only:
                - main
    jobs:
      - build:
          context: docker
